[package]

name = "dbus_copy"
version = "19.11.21"
authors = ["David Henningsson <diwic@ubuntu.com>"]

description = "Bindings to D-Bus, which is a bus commonly used on Linux for inter-process communication."
repository = "https://github.com/diwic/dbus-rs"
documentation = "http://docs.rs/dbus"
keywords = ["D-Bus", "DBus", "IPC"]
license = "Apache-2.0/MIT"
categories = ["os::unix-apis", "api-bindings"]
readme = "../README.md"
edition = "2018"

[dependencies]
libc = "0.2.60"
libdbus-sys = { version = "0.2" }

[dev-dependencies]
tempfile = "3"

[features]
no-string-validation = []

[badges]
is-it-maintained-open-issues = { repository = "diwic/dbus-rs" }
is-it-maintained-issue-resolution = { repository = "diwic/dbus-rs" }
travis-ci = { repository = "diwic/dbus-rs" }
maintenance = { status = "actively-developed" }
