name: Code Style

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@master
        with:
          rust-version: nightly
      - uses: actions/checkout@master
      - name: Check for leftover println
        run: ./tests/left_over_println.sh
      - name: Check formatting
        run: cargo +nightly fmt --all -- --check
