name: Build and Test

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: hecrj/setup-rust-action@master
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
    - name: Build
      run: cargo test
